### PR TITLE
Rename async to async_mode for python 3.7 compatibility

### PR DESCRIPTION
**Pull request by michael-k**
This PR should not break backwards compatibility for anyone using pylama as a command line tool.  It is however breaking for anyone importing from `pylama.async` or relying on the existence of `options.async`.

Fixes klen/pylama#89

This PR is based on PR #112 by @maxnordlund and includes his commits.

### CODE REVIEW

**Comment by michael-k** [comment]
@klen Can you please merge and release this?  Python 3.7 will be released at the end of this month, see https://www.python.org/dev/peps/pep-0537/#schedule.

**Comment by michael-k** [comment]
ping @klen 
Python 3.7 was released a week ago and I would really appreciate it, if you could release a 3.7-compatible version.

**Comment by Deimos** [comment]
Unfortunately pylama seems to be effectively unmaintained now. From what I've seen, issues/PRs/pings on this repo and some of the plugins haven't been getting any responses in almost a year.

Python 3.7 incompatibility will probably be the nudge I needed to either fork and fix up a few things myself, or to switch to something else (possibly just running the checkers separately).

**Comment by devnore** [comment]
ping @klen !

**Comment by romanosipenko** [comment]
ping @klen

**Comment by fmv1992** [comment]
AFAIK Klen does not maintain this project. python-mode uses my own branch because I can accept/review PRs in a timely way.

If there are other more commited devs in this project we can change python-mode's pylama to it.

**Comment by cscutcher** [comment]
Just wondering if anyone is considering alternatives? https://github.com/PyCQA/prospector seems a bit more lively.

**Comment by susam** [comment]
I have pulled the changes in this pull request into [Pylava](https://github.com/pyfocus/pylava). Pylava is intended to be a community maintained fork of Pylama. It works with Python 3.7.

Enter the following command to install Pylava:

    pip install pylava

With Python 3, you may need to enter the following command instead:

    pip3 install pylava

After that you need to use `pylava` instead of `pylama`, for example, by updating your `pylama` commands to `pylava` commands.

Thanks to @michael-k for this pull request.

**Comment by michael-k** [comment]
See klen/pylama#129

**Comment by klen** [comment]
@michael-k Thank you for the work!

**Pull request closed without merging**
