### PR TITLE
Fix skip param

### LINKED ISSUE #133: Skip line comment doesn't work with version 7.6.4
I'm using `# pylama:skip=1` to skip code checking.
But it doesn't work when I upgrade to version 7.6.4.

```
src/config.py:1:1: E800: Found commented out code: # pylama: skip=1 [eradicate]
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64525881-skip-line-comment-doesn-t-work-with-version-7-6-4?utm_campaign=plugin&utm_content=tracker%2F394650&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F394650&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by CharAct3**
Fix #133.

### CODE REVIEW

**Comment by delfick** [comment]
Is there a reason this one was never merged?

I can't use the latest pylama because I need the skip parameter to work

**Comment by claco** [comment]
@delfick Did you ever find a workaround for this other than using an old old version?

**Comment by delfick** [comment]
Unfortunately not :(

I just use pylama==7.5.5

**Comment by klen** [comment]
@CharAct3 Thank you for the PR

**Pull request closed without merging**
